// Generated by LiveScript 1.6.0
var Bmg, restrict, rename, one, yByX;
Bmg = require('../dist/bmg.cjs');
restrict = curry$(function(predicate, relation){
  return Bmg.restrict(relation, predicate);
});
rename = curry$(function(renaming, relation){
  return Bmg.rename(relation, renaming);
});
one = function(relation){
  return Bmg.one(relation);
};
yByX = curry$(function(y, x, relation){
  return Bmg.yByX(y, x, relation);
});
module.exports = {
  Bmg: Bmg.Bmg,
  restrict: restrict,
  rename: rename,
  one: one,
  yByX: yByX
};
function curry$(f, bound){
  var context,
  _curry = function(args) {
    return f.length > 1 ? function(){
      var params = args ? args.concat() : [];
      context = bound ? context || this : this;
      return params.push.apply(params, arguments) <
          f.length && arguments.length ?
        _curry.call(context, params) : f.apply(context, params);
    } : f;
  };
  return _curry();
}