// Generated by LiveScript 1.6.0
var ref$, restrict, rename, one, suppliers, result;
ref$ = require('./bmg-ls.cjs'), restrict = ref$.restrict, rename = ref$.rename, one = ref$.one;
suppliers = [
  {
    sid: 'S1',
    name: 'Smith',
    status: 20,
    city: 'London'
  }, {
    sid: 'S2',
    name: 'Jones',
    status: 10,
    city: 'Paris'
  }, {
    sid: 'S3',
    name: 'Blake',
    status: 30,
    city: 'Paris'
  }, {
    sid: 'S4',
    name: 'Clark',
    status: 20,
    city: 'London'
  }, {
    sid: 'S5',
    name: 'Adams',
    status: 30,
    city: 'Athens'
  }
];
result = one(
restrict({
  city: 'Paris'
})(
rename({
  sid: 'id',
  name: 'lastname'
})(
restrict(function(_){
  return _.status > 20;
})(
suppliers))));
console.log(result);